* NetEase Music Plug for Emacs
  
** Installnation
If you use melpa, install emms from melpa. But melpa is blocked in China, so please use elpa instead.

1. Download music.el from github and add this file to your load-path.

2. Get your user id.
   You need to request this url: http://119.23.207.231:3000/login/cellphone?phone=YOUR-PHONE-NUMBER&password=YOUR-PASSWORD
   Replace  YOUR-PHONE-NUMBER and YOUR-PASSWORD.
   Get id from 'account'.

3. Config.
   #+BEGIN_SRC elisp
   (require 'music)
   
   (setq netease-music-username "17826856902")
   
   (setq netease-music-user-password "w1234567")
   
   (setq netease-music-user-id "YOUR-USER-ID")
   #+END_SRC

4. Enjoy.

** Useage

- =M-x netease-music-init-frame= Initialize netease-music buffer.
- =M-x netease-music-jump-into= Jump into the playlist. You can use "Enter" too if you use evil.
- =M-x netease-music-jump-into= Play current song. You can use "Enter" too if you use evil.
- =M-x netease-music-play-next= Play next song in this playlist. You can use "n" too if you use evil.
- =M-x netease-music-search= Search songs.
- =M-x netease-music-i-like-it= Collect song to your "favoriate song list".
  
** Functions to be improved 
- Get player's infomation.
- Use macro to simplification.
- 使用Elisp破解而不依赖外部的API服务
- 新建一个Process而不依赖EMMS
    参考 [[https://github.com/zhengyuli/WangyiMusic][WangyiMusic]] 。
